server:
  port: 8166
  servlet:
    context-path: /web-market-carts
utils:
  cart:
    prefix: SPRING_WEB_
integrations:
  core-service:
    url: http://localhost:5555/core
  recom-service:
    url: http://localhost:5555/recom
constant:
  recom-send: 600000 # интервал отправки статистики по товарам в recom-service